### PR TITLE
update home page

### PR DESCRIPTION
**Pull request by kweav**
Update home page with a description of the design of the survey as well as a summary of the results

### CODE REVIEW

**Comment by kweav** [comment]
I'm not sure why the banner stopped rendering :/

**Comment by carriewright11** [comment]
Looks good! I think we can get rid of the text that was for the banner - I think it is ok not to have it

**Comment by kweav** [comment]
Great! Thank you! I'll remove the banner and then merge

**Comment by carriewright11** [comment]
sounds great!

**Pull request merged**
